-i4 -npsl -di0 -br -nce -d0 -cli0 -npcs -nfc1 -nut -ncs
-Tjk_env_t
-Tjk_worker_t
-Tjk_worker_env_t
-Tjk_endpoint_t
-Tjk_channel_t
-Tjk_sockbuf_t
-Tjk_msg_t
-Tjk_msg_buf_t
-Tjk_map_t
-Tjk_uri_worker_map_t
-Tjk_pool_t
-Tjk_pool_atom_t
-Tjk_logger_t
-Tjk_ws_service_t
-Tjk_context_item_t
-Tjk_context_t
-Tjk_login_service_t
