github:
  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
          - "1.3.x"
          - "1.2.x"
          - "1.1.x"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
